# Generated by Django 4.0 on 2024-03-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0002_alter_user_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables_app.employer', verbose_name='Работодатель'),
        ),
    ]
