# Generated by Django 4.0 on 2024-03-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0004_institute_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='busyness',
            field=models.CharField(choices=[('FULL', 'Полная занятось'), ('FLEXIBLE', 'Гибкий график'), ('SHIFT_WORK', 'Сменный график')], default='FULL', max_length=10, verbose_name='Занятость'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='skills',
            field=models.CharField(default=1, max_length=255, verbose_name='Ключевые навыки'),
            preserve_default=False,
        ),
    ]
