# Generated by Django 4.0 on 2024-03-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0005_vacation_address_vacation_busyness_vacation_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables_app.user', verbose_name='Студент')),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables_app.vacation', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклики',
                'verbose_name_plural': 'Отклики',
                'db_table': 'reply',
            },
        ),
    ]
