# Generated by Django 4.0 on 2024-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0007_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram',
            field=models.CharField(default=1, max_length=50, verbose_name='Телеграмм'),
            preserve_default=False,
        ),
    ]
