# Generated by Django 4.0 on 2024-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0009_student_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
