# Generated by Django 4.0 on 2024-04-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0010_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='town',
        ),
    ]
